using System.Data;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using MOODJOURNAL.Models;
using Npgsql;

namespace MOODJOURNAL.Services
{
    public class DatabaseService
    {
        private readonly NpgsqlDataSource _dataSource;
        private readonly SemaphoreSlim _semaphore = new(1, 1);
        private bool _initialized;

        public DatabaseService(IConfiguration configuration)
        {
            var connectionString = configuration.GetConnectionString("Supabase")
                ?? Environment.GetEnvironmentVariable("SUPABASE_DB_URL")
                ?? throw new InvalidOperationException(
                    "Missing Supabase database connection string. Set ConnectionStrings__Supabase or SUPABASE_DB_URL.");

            var builder = new NpgsqlDataSourceBuilder(connectionString);
            _dataSource = builder.Build();
        }

        private async Task EnsureInitializedAsync()
        {
            if (_initialized)
                return;

            await _semaphore.WaitAsync();
            try
            {
                if (_initialized)
                    return;

                await using var conn = await _dataSource.OpenConnectionAsync();

                var schemaSql = """
                    CREATE TABLE IF NOT EXISTS users (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username text NOT NULL UNIQUE,
                        password text NOT NULL,
                        created_at timestamp NOT NULL DEFAULT NOW()
                    );

                    CREATE TABLE IF NOT EXISTS categories (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id integer NOT NULL,
                        name text NOT NULL,
                        color text NOT NULL DEFAULT '#C46210',
                        is_default boolean NOT NULL DEFAULT FALSE,
                        created_at timestamp NOT NULL DEFAULT NOW()
                    );

                    CREATE TABLE IF NOT EXISTS journal_entries (
                        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        date timestamp NOT NULL,
                        user_id integer NOT NULL,
                        title text NOT NULL,
                        content text NOT NULL,
                        content_raw text NOT NULL,
                        primary_mood text NOT NULL,
                        secondary_moods_json text NOT NULL DEFAULT '[]',
                        tags_json text NOT NULL DEFAULT '[]',
                        category text NOT NULL DEFAULT '',
                        created_at timestamp NOT NULL DEFAULT NOW(),
                        updated_at timestamp NOT NULL DEFAULT NOW()
                    );

                    CREATE INDEX IF NOT EXISTS idx_categories_user_id ON categories (user_id);
                    CREATE INDEX IF NOT EXISTS idx_journal_entries_user_id ON journal_entries (user_id);
                    CREATE INDEX IF NOT EXISTS idx_journal_entries_date ON journal_entries (date);
                    CREATE INDEX IF NOT EXISTS idx_journal_entries_user_date ON journal_entries (user_id, date);
                    """;

                await using (var cmd = conn.CreateCommand())
                {
                    cmd.CommandText = schemaSql;
                    await cmd.ExecuteNonQueryAsync();
                }

                await SeedDefaultCategoriesAsync(conn);
                _initialized = true;
            }
            finally
            {
                _semaphore.Release();
            }
        }

        private static JournalEntry MapJournalEntry(NpgsqlDataReader reader)
        {
            var entry = new JournalEntry
            {
                Id = reader.GetInt32(reader.GetOrdinal("id")),
                Date = reader.GetDateTime(reader.GetOrdinal("date")),
                UserId = reader.GetInt32(reader.GetOrdinal("user_id")),
                Title = reader.GetString(reader.GetOrdinal("title")),
                Content = reader.GetString(reader.GetOrdinal("content")),
                ContentRaw = reader.GetString(reader.GetOrdinal("content_raw")),
                PrimaryMood = reader.GetString(reader.GetOrdinal("primary_mood")),
                SecondaryMoodsJson = reader.GetString(reader.GetOrdinal("secondary_moods_json")),
                TagsJson = reader.GetString(reader.GetOrdinal("tags_json")),
                Category = reader.GetString(reader.GetOrdinal("category")),
                CreatedAt = reader.GetDateTime(reader.GetOrdinal("created_at")),
                UpdatedAt = reader.GetDateTime(reader.GetOrdinal("updated_at"))
            };

            entry.SecondaryMoods = JsonSerializer.Deserialize<List<string>>(entry.SecondaryMoodsJson) ?? new();
            entry.Tags = JsonSerializer.Deserialize<List<string>>(entry.TagsJson) ?? new();
            return entry;
        }

        private static Category MapCategory(NpgsqlDataReader reader)
        {
            return new Category
            {
                Id = reader.GetInt32(reader.GetOrdinal("id")),
                UserId = reader.GetInt32(reader.GetOrdinal("user_id")),
                Name = reader.GetString(reader.GetOrdinal("name")),
                Color = reader.GetString(reader.GetOrdinal("color")),
                IsDefault = reader.GetBoolean(reader.GetOrdinal("is_default")),
                CreatedAt = reader.GetDateTime(reader.GetOrdinal("created_at"))
            };
        }

        private static User MapUser(NpgsqlDataReader reader)
        {
            return new User
            {
                Id = reader.GetInt32(reader.GetOrdinal("id")),
                Username = reader.GetString(reader.GetOrdinal("username")),
                Password = reader.GetString(reader.GetOrdinal("password")),
                CreatedAt = reader.GetDateTime(reader.GetOrdinal("created_at"))
            };
        }

        private async Task SeedDefaultCategoriesAsync(NpgsqlConnection conn)
        {
            var defaultNames = new[] { "Personal", "Work", "Health", "Travel", "Fitness", "Self-care" };

            foreach (var name in defaultNames)
            {
                await using var cmd = conn.CreateCommand();
                cmd.CommandText = """
                    INSERT INTO categories (user_id, name, color, is_default)
                    SELECT 0, @name, '#C46210', TRUE
                    WHERE NOT EXISTS (
                        SELECT 1 FROM categories
                        WHERE user_id = 0 AND LOWER(name) = LOWER(@name)
                    );
                    """;
                cmd.Parameters.AddWithValue("name", name);
                await cmd.ExecuteNonQueryAsync();
            }
        }

        public async Task<List<JournalEntry>> GetEntriesAsync(int userId)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                SELECT id, date, user_id, title, content, content_raw, primary_mood,
                       secondary_moods_json, tags_json, category, created_at, updated_at
                FROM journal_entries
                WHERE user_id = @user_id
                ORDER BY date DESC;
                """;
            cmd.Parameters.AddWithValue("user_id", userId);

            var entries = new List<JournalEntry>();
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                entries.Add(MapJournalEntry(reader));
            }

            return entries;
        }

        public async Task<JournalEntry?> GetEntryByDateAsync(DateTime date, int userId)
        {
            await EnsureInitializedAsync();

            var startOfDay = date.Date;
            var endOfDay = startOfDay.AddDays(1);

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                SELECT id, date, user_id, title, content, content_raw, primary_mood,
                       secondary_moods_json, tags_json, category, created_at, updated_at
                FROM journal_entries
                WHERE user_id = @user_id
                  AND date >= @start_of_day
                  AND date < @end_of_day
                ORDER BY date DESC
                LIMIT 1;
                """;
            cmd.Parameters.AddWithValue("user_id", userId);
            cmd.Parameters.AddWithValue("start_of_day", startOfDay);
            cmd.Parameters.AddWithValue("end_of_day", endOfDay);

            await using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow);
            if (await reader.ReadAsync())
            {
                return MapJournalEntry(reader);
            }

            return null;
        }

        public async Task<int> SaveEntryAsync(JournalEntry entry)
        {
            await EnsureInitializedAsync();

            entry.SecondaryMoodsJson = JsonSerializer.Serialize(entry.SecondaryMoods);
            entry.TagsJson = JsonSerializer.Serialize(entry.Tags);
            entry.UpdatedAt = DateTime.Now;

            await using var conn = await _dataSource.OpenConnectionAsync();

            if (entry.Id != 0)
            {
                await using var updateCmd = conn.CreateCommand();
                updateCmd.CommandText = """
                    UPDATE journal_entries
                    SET date = @date,
                        user_id = @user_id,
                        title = @title,
                        content = @content,
                        content_raw = @content_raw,
                        primary_mood = @primary_mood,
                        secondary_moods_json = @secondary_moods_json,
                        tags_json = @tags_json,
                        category = @category,
                        updated_at = @updated_at
                    WHERE id = @id;
                    """;
                updateCmd.Parameters.AddWithValue("id", entry.Id);
                updateCmd.Parameters.AddWithValue("date", entry.Date);
                updateCmd.Parameters.AddWithValue("user_id", entry.UserId);
                updateCmd.Parameters.AddWithValue("title", entry.Title);
                updateCmd.Parameters.AddWithValue("content", entry.Content);
                updateCmd.Parameters.AddWithValue("content_raw", entry.ContentRaw);
                updateCmd.Parameters.AddWithValue("primary_mood", entry.PrimaryMood);
                updateCmd.Parameters.AddWithValue("secondary_moods_json", entry.SecondaryMoodsJson);
                updateCmd.Parameters.AddWithValue("tags_json", entry.TagsJson);
                updateCmd.Parameters.AddWithValue("category", entry.Category ?? string.Empty);
                updateCmd.Parameters.AddWithValue("updated_at", entry.UpdatedAt);

                return await updateCmd.ExecuteNonQueryAsync();
            }

            entry.CreatedAt = DateTime.Now;

            await using var insertCmd = conn.CreateCommand();
            insertCmd.CommandText = """
                INSERT INTO journal_entries
                    (date, user_id, title, content, content_raw, primary_mood,
                     secondary_moods_json, tags_json, category, created_at, updated_at)
                VALUES
                    (@date, @user_id, @title, @content, @content_raw, @primary_mood,
                     @secondary_moods_json, @tags_json, @category, @created_at, @updated_at)
                RETURNING id;
                """;
            insertCmd.Parameters.AddWithValue("date", entry.Date);
            insertCmd.Parameters.AddWithValue("user_id", entry.UserId);
            insertCmd.Parameters.AddWithValue("title", entry.Title);
            insertCmd.Parameters.AddWithValue("content", entry.Content);
            insertCmd.Parameters.AddWithValue("content_raw", entry.ContentRaw);
            insertCmd.Parameters.AddWithValue("primary_mood", entry.PrimaryMood);
            insertCmd.Parameters.AddWithValue("secondary_moods_json", entry.SecondaryMoodsJson);
            insertCmd.Parameters.AddWithValue("tags_json", entry.TagsJson);
            insertCmd.Parameters.AddWithValue("category", entry.Category ?? string.Empty);
            insertCmd.Parameters.AddWithValue("created_at", entry.CreatedAt);
            insertCmd.Parameters.AddWithValue("updated_at", entry.UpdatedAt);

            var newId = (int)(await insertCmd.ExecuteScalarAsync() ?? 0);
            entry.Id = newId;
            return newId;
        }

        public async Task<int> DeleteEntryAsync(JournalEntry entry)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = "DELETE FROM journal_entries WHERE id = @id;";
            cmd.Parameters.AddWithValue("id", entry.Id);
            return await cmd.ExecuteNonQueryAsync();
        }

        public async Task<List<JournalEntry>> SearchEntriesAsync(string query, int userId)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                SELECT id, date, user_id, title, content, content_raw, primary_mood,
                       secondary_moods_json, tags_json, category, created_at, updated_at
                FROM journal_entries
                WHERE user_id = @user_id
                  AND (title ILIKE '%' || @query || '%' OR content_raw ILIKE '%' || @query || '%')
                ORDER BY date DESC;
                """;
            cmd.Parameters.AddWithValue("user_id", userId);
            cmd.Parameters.AddWithValue("query", query);

            var entries = new List<JournalEntry>();
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                entries.Add(MapJournalEntry(reader));
            }

            return entries;
        }

        public async Task<List<JournalEntry>> GetEntriesInDateRangeAsync(DateTime start, DateTime end, int userId)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                SELECT id, date, user_id, title, content, content_raw, primary_mood,
                       secondary_moods_json, tags_json, category, created_at, updated_at
                FROM journal_entries
                WHERE user_id = @user_id
                  AND date >= @start_date
                  AND date <= @end_date
                ORDER BY date ASC;
                """;
            cmd.Parameters.AddWithValue("user_id", userId);
            cmd.Parameters.AddWithValue("start_date", start);
            cmd.Parameters.AddWithValue("end_date", end);

            var entries = new List<JournalEntry>();
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                entries.Add(MapJournalEntry(reader));
            }

            return entries;
        }

        public async Task<List<Category>> GetCategoriesAsync(int userId)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                SELECT id, user_id, name, color, is_default, created_at
                FROM categories
                WHERE user_id = @user_id OR user_id = 0
                ORDER BY is_default DESC, name ASC;
                """;
            cmd.Parameters.AddWithValue("user_id", userId);

            var categories = new List<Category>();
            await using var reader = await cmd.ExecuteReaderAsync();
            while (await reader.ReadAsync())
            {
                categories.Add(MapCategory(reader));
            }

            return categories;
        }

        public async Task<int> SaveCategoryAsync(Category category)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();

            if (category.Id != 0)
            {
                await using var updateCmd = conn.CreateCommand();
                updateCmd.CommandText = """
                    UPDATE categories
                    SET user_id = @user_id,
                        name = @name,
                        color = @color,
                        is_default = @is_default,
                        created_at = @created_at
                    WHERE id = @id;
                    """;
                updateCmd.Parameters.AddWithValue("id", category.Id);
                updateCmd.Parameters.AddWithValue("user_id", category.UserId);
                updateCmd.Parameters.AddWithValue("name", category.Name);
                updateCmd.Parameters.AddWithValue("color", category.Color);
                updateCmd.Parameters.AddWithValue("is_default", category.IsDefault);
                updateCmd.Parameters.AddWithValue("created_at", category.CreatedAt);

                return await updateCmd.ExecuteNonQueryAsync();
            }

            category.CreatedAt = DateTime.Now;

            await using var insertCmd = conn.CreateCommand();
            insertCmd.CommandText = """
                INSERT INTO categories (user_id, name, color, is_default, created_at)
                VALUES (@user_id, @name, @color, @is_default, @created_at)
                RETURNING id;
                """;
            insertCmd.Parameters.AddWithValue("user_id", category.UserId);
            insertCmd.Parameters.AddWithValue("name", category.Name);
            insertCmd.Parameters.AddWithValue("color", category.Color);
            insertCmd.Parameters.AddWithValue("is_default", category.IsDefault);
            insertCmd.Parameters.AddWithValue("created_at", category.CreatedAt);

            var newId = (int)(await insertCmd.ExecuteScalarAsync() ?? 0);
            category.Id = newId;
            return newId;
        }

        public async Task<int> DeleteCategoryAsync(Category category)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = "DELETE FROM categories WHERE id = @id;";
            cmd.Parameters.AddWithValue("id", category.Id);
            return await cmd.ExecuteNonQueryAsync();
        }

        public async Task<User?> GetUserAsync(string username)
        {
            await EnsureInitializedAsync();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                SELECT id, username, password, created_at
                FROM users
                WHERE LOWER(username) = LOWER(@username)
                LIMIT 1;
                """;
            cmd.Parameters.AddWithValue("username", username);

            await using var reader = await cmd.ExecuteReaderAsync(CommandBehavior.SingleRow);
            if (await reader.ReadAsync())
            {
                return MapUser(reader);
            }

            return null;
        }

        public async Task<int> CreateUserAsync(User user)
        {
            await EnsureInitializedAsync();

            user.Username = user.Username.Trim().ToLowerInvariant();
            user.CreatedAt = DateTime.Now;

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                INSERT INTO users (username, password, created_at)
                VALUES (@username, @password, @created_at)
                RETURNING id;
                """;
            cmd.Parameters.AddWithValue("username", user.Username);
            cmd.Parameters.AddWithValue("password", user.Password);
            cmd.Parameters.AddWithValue("created_at", user.CreatedAt);

            var newId = (int)(await cmd.ExecuteScalarAsync() ?? 0);
            user.Id = newId;
            return newId;
        }

        public async Task<int> UpdateUserAsync(User user)
        {
            await EnsureInitializedAsync();

            user.Username = user.Username.Trim().ToLowerInvariant();

            await using var conn = await _dataSource.OpenConnectionAsync();
            await using var cmd = conn.CreateCommand();
            cmd.CommandText = """
                UPDATE users
                SET username = @username,
                    password = @password,
                    created_at = @created_at
                WHERE id = @id;
                """;
            cmd.Parameters.AddWithValue("id", user.Id);
            cmd.Parameters.AddWithValue("username", user.Username);
            cmd.Parameters.AddWithValue("password", user.Password);
            cmd.Parameters.AddWithValue("created_at", user.CreatedAt);

            return await cmd.ExecuteNonQueryAsync();
        }
    }
}
